apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: app
  name: php-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
      - image: http://13.57.192.114:8082/app:1.20
        name: app
        ports: 
        - name: app
          containerPort: 8085
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: app
  name: app
spec:
  type: NodePort
  ports:
    - port: 8085
      targetPort: 8085
  selector:
    name: app
---
