---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: php-app
  namespace: default
  labels:
    app: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-app
        image: "414026235762.dkr.ecr.us-west-1.amazonaws.com/php-app:latest"
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: php-app
  namespace: default
spec:
  selector:
    app: php-app
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 3000
    port: 8088