apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8: web
  template:
    metadata:
      labels:
        k8: web
    spec:
      containers:
      - name: php
        image: 414026235762.dkr.ecr.us-west-1.amazonaws.com/php-app:latest
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: php
  namespace: default
spec:
  type: NodePort
  selector:
    k8: web
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001