apiVersion: v1
kind: Deployment
metadata:
  labels:
    name: phpapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: phpapp
    spec:
      containers:
      - image: 414026235762.dkr.ecr.us-west-1.amazonaws.com/php-app
        name: phpapp
        ports: 
        - name: phpapp
          containerPort: 8085
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: phpapp
  name: phpapp
spec:
  type: NodePort
  ports:
    - port: 8086
      targetPort: 8086
  selector:
    name: phpapp
---