apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpapp
  labels:
    app: phpapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpapp
  template:
    metadata:
      labels:
        app: phpapp
    spec:
      containers:
      - name: phpapp
        image: 414026235762.dkr.ecr.us-west-1.amazonaws.com/php-app
        ports:
        - containerPort: 80
        
        
---

apiVersion: v1
kind: Service
metadata:
  labels:
    name: phpapp
  name: phpapp
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: phpapp
---